# Site
name: "The Cloud Bee Blog"
title: "The Cloud Bee Blog"
description: "Your 3 min reads for everything cloud..."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
medium: 'https://medium.com/@amrojsandhu'
google_analytics: 'UA-185024489-1'
disqus: 'thecloudbee'
mailchimp-list: 'https://mailchi.mp/0104833fd31d/subscribe-to-the-cloud-bee-blog'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  amroj:
    name: Amroj Sandhu
    display_name: Amroj Sandhu
    gravatar: 6f4230d6fbdfe22aea2bdcab04f12a40
    email: amrojpals+thecloudbee@gmail.com
    web: https://www.linkedin.com/in/amrojsandhu/
    twitter: https://twitter.com/amrojsandhu
    medium: https://medium.com/@amrojsandhu
    description: "Author of #thecloudbee blog! Works as a software engineer at Expedia."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Filtering Content
future              : true
unpublished         : true
