name: Auto Publish the blog
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # Monday, 10:30 AM IST i.e. Monday, 5:00 AM UTC
    # https://crontab.guru/#12_5_*_*_1
    - cron: 12 5 * * 1

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
