name: Auto Publish the blog
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # Monday, 10:30 AM IST i.e. Sunday, 5:00 PM UTC
    # https://crontab.guru/#0_17_*_*_0
    - cron: 0 17 * * 0

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}