name: Auto Publish the blog
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # Monday, 9:30 AM IST i.e. Monday, 4:00 AM UTC
    # https://crontab.guru/#0_4_*_*_1
    - cron: 0 4 * * 1

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
