name: Image Actions

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'assets/images/202*/*.png'
      - 'assets/images/202*/*.jpg'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Image Compression
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: 80
          pngQuality: 80
          webpQuality: 80
          ignorePaths: node_modules/**