name: Post on Medium

on:
  push:
    branches: [master]
    paths:
      - '.medium/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: medium_new_files
        uses: trilom/file-changes-action@v1.2.4
      - run: |
          for changed_file in ${{ steps.file_changes.outputs.files_modified }}; do
            echo "Posting file to Medium: ${changed_file}."
          done
      - uses: InfraWay/post-medium-action@v1.1.1
        with:
          app_id: ${{ secrets.MEDIUM_APP_ID }}
          app_secret: ${{ secrets.MEDIUM_APP_SECRET }}
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          markdown_file: ${{ steps.file_changes.outputs.files_modified }}
          base_url: https://thecloudbee.blog/
